name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
      - wandb
      - mlflow
      - ipython
      - notebook
      - jupyter
      - cookiecutter
      - hydra-core
      - matplotlib
      - pandas
   